/**
 * Curated dataset of famous/notable Indian IPOs that people search for.
 * These are hardcoded with accurate data because they listed in previous years
 * (2020-2024) and aren't in the live 2025-2026 upstream feeds.
 *
 * This replaces the old substring-matching approach which caused false positives
 * (e.g. "Metalic Technoforge" matching "metal").
 */
const { computeScore } = require('./scoring');

const CURATED_FAMOUS_IPOS = [
  {
    id: 'famous-zomato',
    name: 'Zomato Ltd.',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2021-07-14',
    closeDate: '2021-07-16',
    listingDate: '2021-07-23',
    issuePrice: 76,
    issueAmountCr: 9375,
    subscriptionX: 38.25,
    listingGainPct: 52.63,
    marketPrice: 124.9,
    pePost: null,
    ronw: null,
    nseSymbol: 'ZOMATO',
    isin: 'INE758T01015',
    status: 'listed',
    blurb: "India's leading food delivery platform. Listed July 2021 with 52% listing gain.",
  },
  {
    id: 'famous-swiggy',
    name: 'Swiggy Ltd.',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2024-11-06',
    closeDate: '2024-11-08',
    listingDate: '2024-11-13',
    issuePrice: 390,
    issueAmountCr: 11327,
    subscriptionX: 3.59,
    listingGainPct: 17.44,
    marketPrice: 455.25,
    pePost: null,
    ronw: null,
    nseSymbol: 'SWIGGY',
    isin: 'INE00H001014',
    status: 'listed',
    blurb: 'Food delivery giant. Listed Nov 2024, gained 17% on debut.',
  },
  {
    id: 'famous-paytm',
    name: 'One97 Communications (Paytm)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2021-11-08',
    closeDate: '2021-11-10',
    listingDate: '2021-11-18',
    issuePrice: 2150,
    issueAmountCr: 18300,
    subscriptionX: 1.89,
    listingGainPct: -9.21,
    marketPrice: 925.6,
    pePost: null,
    ronw: null,
    nseSymbol: 'PAYTM',
    isin: 'INE988T01018',
    status: 'listed',
    blurb: "Fintech pioneer. India's largest IPO at the time (2021).",
  },
  {
    id: 'famous-lic',
    name: 'Life Insurance Corporation (LIC)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2022-05-04',
    closeDate: '2022-05-09',
    listingDate: '2022-05-17',
    issuePrice: 949,
    issueAmountCr: 21008,
    subscriptionX: 2.99,
    listingGainPct: -7.8,
    marketPrice: 630.15,
    pePost: null,
    ronw: null,
    nseSymbol: 'LICI',
    isin: 'INE0J1Y01017',
    status: 'listed',
    blurb: "India's largest IPO ever (₹21,000 Cr). Listed May 2022.",
  },
  {
    id: 'famous-tata-technologies',
    name: 'Tata Technologies Ltd.',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2023-11-22',
    closeDate: '2023-11-24',
    listingDate: '2023-11-30',
    issuePrice: 500,
    issueAmountCr: 3042,
    subscriptionX: 69.43,
    listingGainPct: 140.4,
    marketPrice: 1102.5,
    pePost: null,
    ronw: null,
    nseSymbol: 'TATATECH',
    isin: 'INE142M01025',
    status: 'listed',
    blurb: "Tata Group's engineering services arm. 140% listing gain — one of 2023's best.",
  },
  {
    id: 'famous-hyundai',
    name: 'Hyundai Motor India Ltd.',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2024-10-15',
    closeDate: '2024-10-17',
    listingDate: '2024-10-22',
    issuePrice: 1960,
    issueAmountCr: 27859,
    subscriptionX: 1.93,
    listingGainPct: -7.16,
    marketPrice: 1819.6,
    pePost: null,
    ronw: null,
    nseSymbol: 'HYUNDAI',
    isin: 'INE0V6F01027',
    status: 'listed',
    blurb: "India's 2nd largest IPO ever. Listed Oct 2024.",
  },
  {
    id: 'famous-delhivery',
    name: 'Delhivery Ltd.',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2022-05-11',
    closeDate: '2022-05-13',
    listingDate: '2022-05-24',
    issuePrice: 487,
    issueAmountCr: 5235,
    subscriptionX: 1.65,
    listingGainPct: 1.36,
    marketPrice: 382.4,
    pePost: null,
    ronw: null,
    nseSymbol: 'DELHIVERY',
    isin: 'INE148O01028',
    status: 'listed',
    blurb: 'Logistics & supply chain leader. Listed May 2022.',
  },
  {
    id: 'famous-nykaa',
    name: 'FSN E-Commerce (Nykaa)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2021-10-28',
    closeDate: '2021-11-01',
    listingDate: '2021-11-10',
    issuePrice: 1125,
    issueAmountCr: 5352,
    subscriptionX: 1.58,
    listingGainPct: 89.2,
    marketPrice: 1240.5,
    pePost: null,
    ronw: null,
    nseSymbol: 'NYKAA',
    isin: 'INE388Y01029',
    status: 'listed',
    blurb: 'Beauty & fashion e-commerce. 89% listing gain in Nov 2021.',
  },
  {
    id: 'famous-sbi-cards',
    name: 'SBI Cards & Payments',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2020-03-02',
    closeDate: '2020-03-05',
    listingDate: '2020-03-16',
    issuePrice: 755,
    issueAmountCr: 10355,
    subscriptionX: 26.39,
    listingGainPct: -9.4,
    marketPrice: 685.25,
    pePost: null,
    ronw: null,
    nseSymbol: 'SBICARD',
    isin: 'INE752E01010',
    status: 'listed',
    blurb: "India's largest credit card issuer. Listed March 2020.",
  },
  {
    id: 'famous-policybazaar',
    name: 'PB Fintech (Policybazaar)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: '2021-11-01',
    closeDate: '2021-11-03',
    listingDate: '2021-11-15',
    issuePrice: 980,
    issueAmountCr: 5625,
    subscriptionX: 16.67,
    listingGainPct: -7.58,
    marketPrice: 458.3,
    pePost: null,
    ronw: null,
    nseSymbol: 'POLICYBZR',
    isin: 'INE417B01024',
    status: 'listed',
    blurb: "India's largest insurance aggregator. Listed Nov 2021.",
  },
  {
    id: 'famous-oyo',
    name: 'Oyo Rooms (Oravel Stays)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: null,
    closeDate: null,
    listingDate: null,
    issuePrice: null,
    issueAmountCr: 8430,
    subscriptionX: null,
    listingGainPct: null,
    marketPrice: null,
    pePost: null,
    ronw: null,
    nseSymbol: null,
    isin: null,
    status: 'upcoming',
    blurb: 'Hospitality unicorn. DRHP filed, IPO expected soon.',
  },
  {
    id: 'famous-jio',
    name: 'Reliance Jio Infocomm',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: null,
    closeDate: null,
    listingDate: null,
    issuePrice: null,
    issueAmountCr: null,
    subscriptionX: null,
    listingGainPct: null,
    marketPrice: null,
    pePost: null,
    ronw: null,
    nseSymbol: null,
    isin: null,
    status: 'upcoming',
    blurb: "India's largest telecom operator. Highly anticipated IPO — expected to be India's biggest ever.",
  },
  {
    id: 'famous-flipkart',
    name: 'Flipkart (Walmart)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: null,
    closeDate: null,
    listingDate: null,
    issuePrice: null,
    issueAmountCr: null,
    subscriptionX: null,
    listingGainPct: null,
    marketPrice: null,
    pePost: null,
    ronw: null,
    nseSymbol: null,
    isin: null,
    status: 'upcoming',
    blurb: 'Walmart-owned e-commerce giant. IPO rumors persist.',
  },
  {
    id: 'famous-phonepe',
    name: 'PhonePe (Walmart)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: null,
    closeDate: null,
    listingDate: null,
    issuePrice: null,
    issueAmountCr: 16000,
    subscriptionX: null,
    listingGainPct: null,
    marketPrice: null,
    pePost: null,
    ronw: null,
    nseSymbol: null,
    isin: null,
    status: 'upcoming',
    blurb: "India's leading UPI payments app. DRHP filed for ₹16,000 Cr IPO.",
  },
  {
    id: 'famous-boat',
    name: 'boAt (Imagine Marketing)',
    category: 'Mainboard',
    exchange: 'BSE, NSE',
    openDate: null,
    closeDate: null,
    listingDate: null,
    issuePrice: null,
    issueAmountCr: null,
    subscriptionX: null,
    listingGainPct: null,
    marketPrice: null,
    pePost: null,
    ronw: null,
    nseSymbol: null,
    isin: null,
    status: 'upcoming',
    blurb: "India's #1 audio wearables brand. IPO expected.",
  },
];

function getFamousIpos() {
  return CURATED_FAMOUS_IPOS.map((ipo) => ({
    ...ipo,
    slug: null,
    source: 'curated',
    score: computeScore({
      subscriptionX: ipo.subscriptionX,
      kpi: { pePost: ipo.pePost, ronw: ipo.ronw },
      financials: {},
      reviews: { subscribe: 0, neutral: 0, avoid: 0 },
      listing: { gainPct: ipo.listingGainPct },
      market: { price: ipo.marketPrice },
      issuePrice: ipo.issuePrice,
      listingDate: ipo.listingDate,
      category: ipo.category,
    }),
  }));
}

module.exports = { getFamousIpos, CURATED_FAMOUS_IPOS };

